services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports: ["8000:8000"]
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports: ["8080:80"]
    depends_on: [backend]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2
    ports: ["3001:3000"]
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: unless-stopped
